# Generated by Django 4.2.2 on 2023-06-17 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(default=datetime.datetime)),
                ('order_total_price', models.DecimalField(decimal_places=2, default=' ', max_digits=7)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('f_name', models.CharField(default='', max_length=100)),
                ('m_name', models.CharField(default='', max_length=100)),
                ('l_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('ssn', models.CharField(max_length=14, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(default='', max_length=100)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managment.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expired_date', models.DateField()),
                ('manufacture_date', models.DateField()),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('supply_date', models.DateField()),
                ('category', models.CharField(choices=[('prescription medications', 'prescription medications'), ('non-prescription medications', 'non-prescription medications'), ('beauty & cosmetics', 'beauty & cosmetics'), ('medical supplies', 'medical supplies'), ('baby and childcare prodects', 'baby and childcare prodects')], max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField(max_length=1000)),
            ],
            options={
                'ordering': ['supply_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('f_name', models.CharField(default='', max_length=100)),
                ('m_name', models.CharField(default='', max_length=100)),
                ('l_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('ssn', models.CharField(max_length=14, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(default=datetime.datetime)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_state', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered')], max_length=10)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.customers')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
