# Generated by Django 4.2.2 on 2023-06-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='customer %y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='prodects %y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='users %y-%m-%d'),
        ),
    ]
