# Generated by Django 4.2.2 on 2023-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_cart_product_item_order_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
