# Generated by Django 4.2.2 on 2023-06-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0014_alter_customers_password_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
